AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  ai-agent-car-price-tool-handler

  Sample SAM Template for  ai-agent-car-price-tool-handler

Resources:
  AICarPriceToolFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: "car-price-tool"
      #Handler: lambda_trigger.lambda_handler
      CodeUri: handler/
      #Runtime: python3.12
      Timeout: 60
      MemorySize: 4096
      Environment:
        Variables:
          PIPELINE_NAME: "CarPricePipeline"
          INPUT_BUCKET: "car-price-data"
          RAW_DATA_PREFIX: "raw_data/"
          PROCESSED_DATA_PREFIX: "processed_data/"
      Architectures:
        - x86_64
      Events:
        AIAgentVideoHandler:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /agent/chat/car-price
            Method: post
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - "sagemaker:StartPipelineExecution"
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "*"

        # OPTIONAL: If your Lambda code also needs direct S3 access
        - Statement:
            - Effect: Allow
              Action:
                - "s3:GetObject"
                - "s3:ListBucket"
                - "s3:PutObject"
              Resource:
                - "arn:aws:s3:::car-price-data"
                - "arn:aws:s3:::car-price-data/*"
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./handler
      DockerTag: v1

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AICarPriceToolApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  AICarPriceToolFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt AICarPriceToolFunction.Arn
  AICarPriceToolFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt AICarPriceToolFunctionRole.Arn
